### ISSUE TITLE
Replace #voice with #other/#bots on the Discord and add bot games

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#128]
**Brief Description**

Replace #voice with #other/#bots in the discord voice category and add a bunch of bots with built in minigames.

**Why do you want the feature?**

Currently, the discord community is lacking on the whole community aspect. At the moment, our discord server feels more like a utility than a place to hang out. While adding a bunch of bot games won't fix that problem entirely, I think it's a step in the right direction.

**Additional context**

Here's a bunch of bots to consider inviting, they have various econ/simulator/tycoon minigames and can be lots of fun.
Idle Miner: https://top.gg/bot/518759221098053634
Gambling Bot: https://top.gg/bot/395385545326592010
BoxBot: https://top.gg/bot/boxbot
OwO Bot: https://top.gg/bot/owo
Taco Shack: https://top.gg/bot/490707751832649738
IdleRPG: https://top.gg/bot/idlerpg

**Comment by vinceingithub** [comment]
It seems that most people in #suggestions want this as I have 5 yes's and two no's.

**Comment by vinceingithub** [comment]
Denied by the community.

**Comment by Pemigrade** [comment]
From #162:
Brief Description
A poker bot on discord with its own channel which could double over as a game-req channel (Possible channel name: #entertainment or #games).

Why do you want the feature?
The poker bot is for when people are bored and on discord. (money is not connected to ig money. Having its own channel would ensure it isn't spammed in #general or something. As Lefty said, it's basically #off-topic but more refined. The channel could also work as a channel for announcing game codes and the like for Among Us, skribbl.io, etc so it doesn't clog up #general. Similarly, there could be some kind of role that people can @ for announcing games, kind of like the sab role (so that way people can immediately see when someone is starting something up). Possible role name: @ games

Additional context
Here is the link for the poker bot: https://top.gg/bot/461791942779338762

**Comment by Qbiksus** [comment]
Brief Description

Implement a more fair resend so end resources are reasonably obtainable. One that resets way more often and random seed each time.

Why do you want the feature?

The current solution is not realistic for the size of the server. It is impossible to get any end resources for people who can't be on at the specific time the border expands or when it resets, because the entire end gets ransacked like it's a BestBuy in the middle of a riot and within a few hours, every thing is gone. One that resets every day or few days would make it much more obtainable for the people who have more than Minecraft to attend to. 

Additional context
This can be done manually with multiverse (don't know if it can be automated with it) and with this resource world plugin: 
https://www.spigotmc.org/resources/%E2%9C%85-resource-world-%E2%9C%85-never-run-out-of-resources-must-have.75994/reviews

**Comment by Pemigrade** [comment]
The following bots were added:
Idle Miner
Gambling Bot
Dankmemer
Mee6
OwO Bot
Taco Shack
