### ISSUE TITLE
A Music Bot For The Staff VC

### ISSUE THREAD

**Issue by HannahOnGithub** [Pemigrade/Acorn#149]
**Brief Description**
For there to be a bot where staff members can listen to music in the staff Vc.

**Why do you want the feature?**

Staff members aren’t permitted to use Rhythm 1 and 2 in the Staff VC.
**Additional context**

**Comment by Pemigrade** [comment]
Denied by both the community and me.

I think the primary intent of staff chat is for discussions among staff. Converting it into a sort of staff hangout may separate them from regular players, which is the last thing I want to do. Since adding a music bot won't help for discussions that have to be held among staff only, I'm denying this suggestion. Voice Chat A, B, and Music will still allow you to listen to music, and they will also allow other players to join in on the listening party.
