### ISSUE TITLE
Redone Resend

### ISSUE THREAD

**Issue by Qbiksus** [Pemigrade/Acorn#164]
**Brief Description**

Implement a more fair resend so end resources are reasonably obtainable. One that resets way more often and random seed each time.

**Why do you want the feature?**

The current solution is not realistic for the size of the server. It is impossible to get any end resources for people who can't be on at the specific time the border expands or when it resets, because the entire end gets ransacked like it's a BestBuy in the middle of a riot and within a few hours, every thing is gone. One that resets every day or few days would make it much more obtainable for the people who have more than Minecraft to attend to.

**Additional context**

This can be done manually with multiverse (don't know if it can be automated with it) and with this resource world plugin:
https://www.spigotmc.org/resources/%E2%9C%85-resource-world-%E2%9C%85-never-run-out-of-resources-must-have.75994/reviews

**Comment by Pemigrade** [comment]
The resend expands constantly. There isn't a specific time that the border expands. If you check frequently, you'll stumble across an unraided end city :) 

While the plugin seems like an easy way to help out with resend creation, it doesn't seem to be able to automate (a) worldguard flags, (b) warp creation, (c) creation of a worldguard region to protect the resend spawn, (d) a bridge from the spawn platform to the main island, and by FAR most importantly (e) chunk pregeneration on a separate server, then moving the resworld over and importing it with Multiverse.

To create the current resend, I created a separate server and installed a chunk pregeneration plugin. I then pregenerated the chunks up in a 20k diameter. A separate server is necessary for this in order to utilize multiple threads and not lag the server. Afterwards, I had to stop the second server, create a folder called resend on the survival server, change the file owner from root to pterodactyl, and then rename the files in /second-server/world_the_end to be in /survival/resend. Next, I logged onto the current server, imported it with /mv import, set up a bunch of worldguard flags, built a small bridge to connect the spawn to the main island, and finally created a worldguard region around the bridge and spawn to prevent people from breaking it.

My intention of telling you all that was that it'd be near-impossible to automate a plugin to do all this, so the changes would all have to be manual.

Disregarding the fact that it'd take a long time to reset the end every few days, I still would have to oppose this suggestion. Elytras and shulker boxes can be obtained in vote crates. I've gotten 2 elytras so far just by voting! However, we intentionally want to preserve the vanilla mechanic of keeping some items rare/difficult to find. Resources can be really easy to get on survival servers, and scarcity is our way of preserving the difficulty of obtaining rare items.
