### ISSUE TITLE
Biannual Server Wipe

### ISSUE THREAD

**Issue by Pamuii** [Pemigrade/Acorn#179]
**Brief Description**
I would like to see a complete server wipe three times a year. This includes regening a new world, wiping economy and player inventory while of course maintaining ranks, and vote rewards.

**Why do you want the feature?**
I believe that doing this will breathe new life into the server. Server decay is a thing on vanilla servers that involves losing players overtime due to a lack of things to do. 

**Additional context**
I've seen this happen multiple times on multiple servers, I don't know if it's completely avoidable, however I think a new world will keep retain more players (marginally).

**Comment by entwastaken** [comment]
will summarize everything said in discord and some extra thoughts of mine, for organization-sake

1. random server wipes will not help bring more life to the server. by "random" i mean server wipes that don't have a serious reason behind them, such as a technical issue like the 1.14 world corruption, or a major update. in fact, it may even cause the opposite effect: people will quit because their hard work gets reset every 4 months for no good reason

2. Primus: "Part of the issue, is those <<going hardcore>> strip a lot of non renewable resources from the server (e.g. villagers) claim protect them, and then leave." , Pamui: "or hoarding shulkers and elytras". 
server wipes won't stop hoarders. it's a normal thing in SMPs: the later you join, the more you will struggle due to joining late, and the further you'll have to travel out to find new terrritory.

3. Pamui: "Long term player retention. In a semi-vanilla server this is not much to do after a set amount of time. You gear up to diamond which takes less than a day in some cases (especially with the help of an economy and some common sense), fight the Ender Dragon (which is low quality if you look at the end rn), and then mess around for a couple days, weeks, or even a month trying to obtain best enchants or netherite armor." 
that's the player's fault for not giving themselves new projects to work on. Minecraft isn't just about maxing out your netherite armour, it's a game about creativity and using the tools at your disposal to expand on your creativity. if you don't want to do that, it is your fault, not the server's for not resetting.

4. Pamui: "If you lose players in the long term, you affect the over atmosphere of the server [...] I’ve logged on almost daily since I joined over two months ago and I’ve seen a steady decrease in player population?" 
keywords there are "joined over two months ago". you joined very soon after the reset to update to 1.16, which brought back a significant amount of players. it's obvious that during those first few weeks and/or months there will be more players than the server's overall average. Acorn's average has been ~30-40 players from what I've seen and heard myself. that average is higher than what it was back in 1.15, and much higher than in 1.14 - due to the horrendous lag this update caused.

5. you're complaining about a drop in playerbase during the winter holidays, when people spend time doing Christmas shopping, preparing for the New Year and spending time with their relatives. it's natural for people to play less during these times.

if there's anything i missed, someone else can mention it.

courtesy of iJoa, Voldechu and me.

**Comment by Pemigrade** [comment]
If the server wipes trianually:
Why would I continue playing if my progress is going to get wiped so soon? At the very least, shouldn't I wait until the start of the next trimester?

Would you suggest some sort of seasonal reward to the top players of a certain map? I.e. top balance gets a rank, top builder gets a rank, etc. A rank doesn't attract people. What more long-term reward does?

The IdleMiner bot has a reward for rebirth/prestige, would something like that encourage people to play?

Isn't an alternative way to accomplish your goals to just remove the world border and players can /rtp to a location a million blocks away when they want to start over? Does everyone have to start over, including this who don't want their progress wiped?

**Comment by Pamuii** [comment]
There has been some progress made in #suggestions which has led to a poll posted in #polls. We collectively decided on a longer period of 6 months.

 _Why would I continue playing if my progress is going to get wiped so soon? At the very least, shouldn't I wait until the start of the next trimester?_

 - If the wipe is increased to a duration of 4-6 months, I feel that provides an adequate amount of time for players to build something of worth. A lot can be done in just a couple months, i.e. _Wynter, Eagleshore, Stop&Shop_ et cetera. 

_Would you suggest some sort of seasonal reward to the top players of a certain map? I.e. top balance gets a rank, top builder gets a rank, etc. A rank doesn't attract people. What more long-term reward does?_

- That actually sounds like a good idea, if executed correctly. Ranks could be distributed to those who meet certain top positions like _top balance gets a rank, top builder gets a rank_ as you stated. In addition or in place of providing ranks you could do a sort of "seasonal" perk for each wipe, i.e. for the Summer 2021 wipe provides all players with access to /nick. For those new players who join the server late we could incorporate mini events halfway through the season for those new players to get additional awards that they originally missed out on. 

_The IdleMiner bot has a reward for rebirth/prestige, would something like that encourage people to play?_

- This also could be added in addition to everything else that was previously mentioned. You could do this by adding requirements to meet in order or obtain a rebirth, in which certain perks could be awarded into the proceeding season. For example: if you are able to raise 100k before wipe, you could be allowed to have 25k of that transferred over to the next season.

_Isn't an alternative way to accomplish your goals to just remove the world border and players can /rtp to a location a million blocks away when they want to start over? Does everyone have to start over, including this who don't want their progress wiped?_

- This is also a good point and would solve all issues relating to the current affair. However this is left up to the decision of the server provider as it may cause additional stress on hardware and services. But I would argue that the wipe would provide a feeling of "freshness" as it is a clean slate for everyone.

**Comment by Abyssmario** [comment]
_Would you suggest some sort of seasonal reward to the top players of a certain map? I.e. top balance gets a rank, top builder gets a rank, etc. A rank doesn't attract people. What more long-term reward does?__

I believe that Runescape™ has a feature that might have some merit to it. Which would be: a money, or gold sink.
In Runescape™, players may "donate" gold to a NPC at spawn or however we choose to go about it, but in essence, the player would be rewarded with a rank depending on how much gold was donated.

For example: https://cdn.discordapp.com/attachments/233785300525121546/792820708631117854/unknown.png

I think this would be quite obvious, and this only apples to one of these points made by Pemi, but it would give players an incentive to spend some gold to keep inflation down on the server, thus giving the wealth players have in game feel a little more _real_.

**Comment by Pemigrade** [comment]
I don't like the NPC idea. Why not just make your balance the equivalent of that NPC? Additionally, we intentionally create inflation on the server. It provides newer players with an advantage over older players and encourages players to buy items with their money.

**Comment by vinceingithub** [comment]
no

**Comment by Pemigrade** [comment]
@vinceingithub is that a "no" as in "I don't support this issue" or something else?

**Comment by vinceingithub** [comment]
@Pemigrade well, what I wanted to say was "this is a terrible idea" but I wasn't about to say that without concisely laying out why I thought that, so I just went with "no" because I thought it would be funny.

**Comment by kakduman** [comment]
Maybe we'll revisit this eventually. Seems like a poor choice at the moment and I can't see too much support for implementing this now.
