### ISSUE TITLE
add separate nickname plugin

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#187]
**Brief Description**
Add this plugin: https://www.spigotmc.org/resources/nicknamer-integrated-api.5341/, which is a nickname plugin.

**Why do you want the feature?**
I understand the reasoning behind the nickname change with EssentialsChat, so there's nothing more to that. However, I feel that nickname is an essential cosmetic (no pun intended), which is why I've sought out this plugin. Hopefully, this is compatible with everything else.

**Additional context**
If this should become too complicated, it would still be great to only give this to people who voted for/donated specifically for /nickname, just like with /fly (but also add the people who voted for it).

Also, although there's no need to, it would be nice to have brief explanations behind sudden changes like this.

**Comment by Pemigrade** [comment]
More plugins = bad. Essentials nicknames are the best in that most plugins are able to integrate with them, but still less than normal. The server can't register those nicknames as *real* people, which is where you run into problems. The only way to fix that would be some weird plugin that subverts authentication servers and gives someone two UUIDs somehow, but that's just asking for game-breaking bugs.

To answer your question with "why the sudden change", we were formerly using MultiChat, a plugin designed to sync chat between servers. While it does what it's supposed to do, there was a critical exploit where players could bypass authentication to send messages under any UUID. The developer didn't handle the exploit well, and publicized it on the plugin's GitHub BEFORE publishing a compiled version. One user noticed that the GitHub contained the leaked exploit, and searched for servers using the plugin. The nature of the exploit was not public until well after the compiled file was published. Therefore, server admins did not know the nature of the exploit, but malicious users did. That's the opposite of what you should do, and it's why Acorn decided to wait 6 hours for the next daily restart rather than restarting immediately. With such a large exploit and such poor handling of the exploit, switching to EssentialsChat is necessary to avoid the chance of having such large future exploits. I hope you can understand.

With that said, I like your suggestion in the additional contexts section. Giving people who bought /nick with votepoints their votepoints back could work. Make a ticket if you want to refund /nick for the current voteshop price. You have until the end of February to do so. I'll edit the announcement in #announcements.

On an unrelated note, I'll also get started on Sabotage. Aiming for Tuesday, thanks Eagle :)
