### ISSUE TITLE
The command /pweather storm allows players to fly using riptide tridents

### ISSUE THREAD

**Issue by Venatriiix** [Pemigrade/Acorn#190]
**Describe the bug**
When a player uses the command /pweather storm, they can use riptide tridents to continuously fly even when it's not raining on the server.

**Expected behavior**
/pweather is intended to be purely cosmetic rather than a game-changing perk, so players should not be able to interact with the rain or fly with their tridents using it.

**To Reproduce**
1.  Use the command /pweather storm (requires you to have Premium Supporter)
2.  Look up and hold right click while there is a trident enchanted with riptide in your hand, then release
3.  Attempt to repeat step 2 before _falling from a high place_

**Comment by Pemigrade** [comment]
https://github.com/EssentialsX/Essentials/issues

**Comment by Pemigrade** [comment]
Just looked through the issues. Looks like there's already one for this: https://github.com/EssentialsX/Essentials/issues/3118.

Nothing can be done about it. I'll keep pweather for premium supporters since it's not too OP. You'll get kicked for flying if you do it long enough, you can't control where you go to a high degree of precision, and at best it's about as powerful as an enderpearl. I'd still advise against using the "bug," though.
