### ISSUE TITLE
Sleep plugin bugs bees

### ISSUE THREAD

**Issue by eddiegtr** [Pemigrade/Acorn#56]
**Describe the bug**
Bees are not coming out of their nests in the overworld due to the sleep plugin

**Expected behavior**
Bees should instantly come out if it's day when you place down a nest

**To Reproduce**
1. Go to overworld and place a nest with bees in it
2. No bees come out
3. Go to the nether and place it down - bees come out right away
4.  Since sleep is not a thing in the nether bees work as intended

**Additional context**

**Comment by Pemigrade** [comment]
It looks like the only way to fix the issue would be to delete the plugin. Pending community approval to see if people would want it deleted.

**Comment by kakd** [comment]
I'm not entirely sure that this is an issue due to DrSleep. DrSleep modifies the time, but doesn't change anything else that could possibly relate to bees. I tested this on a vanilla world and on Acorn. While testing, the night was never skipped. I found that in the vanilla world, the bees would come out after about 30 seconds after placing the beehive down. On Acorn, I stopped waiting after 60 seconds because no bees had come out. See https://imgur.com/a/eNaWC26 for my tests. I think is likely caused by another plugin. More testing is needed.

**Comment by Pemigrade** [comment]
Investigating. DrSleep has been temporarily uninstalled.

**Comment by Pemigrade** [comment]
Issue seems to be due to Spigot 1.16. Only naturally generated beehives have this error. Any user can have their naturally generated beehive replaced by a founder to resolve the issue.

**Comment by Pemigrade** [comment]
Issue may be fixed after the next restart!

**Comment by Pemigrade** [comment]
Confirmed to be fixed. Thank you for testing, Gotti.
