### ISSUE TITLE
Make it so that when the server restarts or crashes all online players are put in the hub instead of disconnecting.

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#61]
**Brief Description**

When the server goes down for any reason all online players would be put in the hub, not disconnected.

**Why do you want the feature?**

Because 9/10 times it doesn't take the server that long to come up and it would be nice to just chill in the hub while we wait.

**Comment by Pemigrade** [comment]
https://www.spigotmc.org/resources/movemenow.17/

**Comment by Pemigrade** [comment]
After looking more into the suggestion, it appears infeasible since the Bungee also restarts at 7AM, meaning all servers go down. The only way to implement it would be to have all players kicked to the lobby at 7AM, then have all players kicked from the server for ~10 seconds at another time. Not implementing the feature means we're able to restart both servers at the same time, and nobody notices that the bungee restarted.
