### ISSUE TITLE
Add warped/crimson stem, netherite ingot to /warp shop

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#62]
**Brief Description**

Allow people to sell warped/crimson stem at the same rate as logs and allow people to sell netherite scrap at at (suggested) rate of 1 scrap for 250.

**Why do you want the feature?**

All other ores and wood types are at the shop but these are mysteriously audited

**Comment by entwastaken** [comment]
i genuinely doubt it would be worth adding netherite ingots to the server shop, because most players don't just have a surplus of netherite ingots. after they finish their tools and armour they only go for more netherite if they are desperate to capitalize on new players, and that's a small minority of the server

**Comment by Pemigrade** [comment]
Items that would likely be removed are pufferfish, tropical fish, and cooked rabbit. Very uncommon items that few new players have

**Comment by Pemigrade** [comment]
Sorry the reason I marked this as needing community approval was to determine which items to remove -- pufferfish, tropical fish, and cooked rabbit?

**Comment by vinceingithub** [comment]
I think that those items are fine.

**Comment by Pemigrade** [comment]
Done!
