### ISSUE TITLE
Mods can't take down warps

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#67]
**Describe the bug**

Mods can not re-name, change the expiry date of, or remove warps.

**Expected behavior**

Mods should be able to re-name, change the expiry date of, and remove warps.

**Comment by kakd** [comment]
I think you might be using the wrong command. Are you doing _/iwarp arename <oldname> <newname>_

Mods can not change the expiry date of warps because they are lacking the permission: iwarp.command.changeexpiration
Mods can not delete warps because they are lacking the permission essentials.delwarp.
I'm not sure if the last two are intentional or not, so I'll let @Pemigrade give the permission.

**Comment by manbrodude** [comment]
I thought it was /awarp rename but /iwarp arename worked; however, your last two points may not be intentional like you said so pemi can take a look at that.

**Comment by Pemigrade** [comment]
Completed. I can verify that the changes were successful in a few hours.
