### ISSUE TITLE
Give permission for players to check TPS

### ISSUE THREAD

**Issue by kohle** [Pemigrade/Acorn#75]
**Brief Description**
Allow players to check TPS (I am assuming it's /tps).

**Why do you want the feature?**
Helps for players to check if there is server lag or just on their end, and in general could help stop people from constantly asking about lag in chat if they can check themselves.

**Comment by Pemigrade** [comment]
Rejected by staff. Most of the time, seeing the TPS is only going to cause some players to complain because 19 is not "good enough," without actually reducing lag.

You can check to see if the lag is server-side by viewing your FPS and your ping. If you have 5 bars in the tablist and a high FPS, the lag is server-side.
