### ISSUE TITLE
Changes to ecotalk / Community Suggestion

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#80]
**Brief Description**

Idea 1). Allow /msg, /r, and /w to reward players money.

Idea 2). Make it more like it was on BF by making it less money gotten per message, and the money is added up and given at the end of the day.

**Why do you want the feature?**

Idea 1). To level the economic playing field for non-english speakers.

Idea 2). It would make it a bit harder to abuse.

**Comment by Pemigrade** [comment]
EcoTalk was designed to encourage players to talk. While whispering may help out players that don't speak English, it can be abused by players to whisper to spam friends for money without being banned for spam. Players that can't speak English may feel more welcome on a server surrounded by people who speak their language. We'll welcome them on Acorn, but we won't intentionally create an exploit in order to help out the few foreign language speakers who may join Acorn.

With the second suggestion, I doubt that the EcoTalk dev would be interested in creating a fork of the plugin to serve this purpose and this purpose only. One additional benefit to EcoTalk immediately giving money is that newbies can make money the instant that they join the server. They wouldn't need to wait a day to reclaim their money. Birdflop's system of giving money at the end of the day could actually be circumvented by relogging, encouraging login spam.
