### ISSUE TITLE
Make the rules have a more immediate presence on the server / Community Suggestion

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#87]
**Brief Description**

Idea 1). "Maybe put a broadcast message to brand new players that tells them to read the /rules, since the tutorial is not functional." -melanellie
Idea 2). "maybe that or a book they have when they spawn that has links to the rules, and maybe links to other sites that contain info that is useful" -gottiii

**Why do you want the feature?**

As of right now, when you first join acorn the rules aren't clearly stated anywhere and you aren't even clearly told to read /rules. This is quite problematic for multiple reasons.

**Comment by Pemigrade** [comment]
A book is planned to be implemented soon since it's harder to overlook compared to a message saying "do /rules".

**Comment by Pemigrade** [comment]
Currently waiting to add it to the newbie starting kit until #13 is completed since the book will include more information that just the rules. For more information regarding the book, you can check [commit 4cbd081](https://github.com/Pemigrade/Acorn/commit/4cbd0816d34250026d5651ab2862f3d384f63118). You can run the Minecraft:give command on a singleplayer world to view the book. Kit futuretools will replace kit tools.

**Comment by Pemigrade** [comment]
Has prerequisite of #159

**Comment by Pemigrade** [comment]
Done, newbies now receive the book in /kit book upon joining, in addition to the regular starting items. Anyone can use /kit book to receive the book. Command has a 5 minute delay.
