### ISSUE TITLE
Bring back the quiz.

### ISSUE THREAD

**Issue by daviddn5** [Pemigrade/Acorn#89]
It would be a good idea to bring back the quiz. It was removed because of players not wanting to do it and leaving, back when we were averaging around 10 players. Now we average like 30+ players, and lots of the new players think greifing is allowed, and we have to constantly inform them of just about everything.

I want this feature, because it would educate new players on the rules of the server, for example a new player greifed my base, thinking it was okay to grief, and saying that its "fair game" when the server rules clearly state that any sort of greifing is forbitten. It would also save lots of time and staff effort.

**Comment by Pemigrade** [comment]
We'll include a book that has a link to our rules instead. We're currently waiting to add it to the newbie starting kit until #13 is completed since the book will include more information that just the rules. For more information regarding the book, you can check [commit 4cbd081](https://github.com/Pemigrade/Acorn/commit/4cbd0816d34250026d5651ab2862f3d384f63118). You can run the Minecraft:give command on a singleplayer world to view the book. Kit futuretools will replace kit tools.
