### ISSUE TITLE
Sabotage: Reduce the chance of wooden swords

### ISSUE THREAD

**Issue by entwastaken** [Pemigrade/Acorn#93]
**Brief Description**
Reduce the chance of receiving wooden swords from chests to balance out the loot.

**Why do you want the feature?**
The chance of wooden swords is abnormally high, even leading to huge streaks of only wooden swords(I, myself, had a streak of **7** wooden swords in a row). Reducing the chance would balance out the loot more and reduce frustration.

**Comment by Pemigrade** [comment]
This is intentional to mimic the original Sabotage, which gave out even more wood stones and even more stone swords than the current version. Potions, bows, iron swords, and special items were even more rare. Current goal is to appeal to the nostalgia of former MCPvP players to collect an initial batch of players for the gamemode.
